### ISSUE TITLE
Pedidos no funciona

### ISSUE THREAD

**Issue by Kamesta** [CostanzoPablo/shell#27]
La funcion pedidos no funciona.

Poder seleccionar por categoria "Juegos" para listar "todos los juegos" o por categoria especifica: "Juegos - Xbox360".

Poder Eliminar items de la lista a reponer (borrarlos de la base de datos o poner maximo y minimo en 0".

Agregar de ser posible un dato como "cantidades vendidas (en los ultimos 6 meses por ej) para tener una idea grafica si es un producto con salida o no.

**Comment by CostanzoPablo** [comment]
Falta lo de cantidades vendidas.... Ponerlo en un issue que no sea este de BUG
