### ISSUE TITLE
Bug: En ventas, no aparece stock restante del producto

### ISSUE THREAD

**Issue by Kamesta** [CostanzoPablo/shell#34]
Ejemplo:

$ 30008/01/2015 10:05efectivo noganet teclado stormer nkb 228 $ 300 Stock:
$ 45008/01/2015 10:15efectivo Saints Row IV: National Treasure - Xbox 360 $ 450 Stock:
$ 5008/01/2015 10:49efectivoDBZ Venta varios $ 50 Stock:

**Comment by CostanzoPablo** [comment]
Fixed
