### ISSUE TITLE
Estadisticas: Upgrades:

### ISSUE THREAD

**Issue by Kamesta** [CostanzoPablo/shell#36]
* Existencias - Crear categoria TODOS entre los items a ver "existencias"

* Existencias - que genere, por local un historial "anual" de X fecha a X fecha puede tomar los intervalos cada 15 dias por ej. y poder exportarlo a un xls.

* Implementar las comisiones entre las estadisticas

* Restas de stock x mes o fecha especifica y que user lo realizo (actualmente en eventos te mezcla todo y es complicado encontrar las restas de stock para control )

* Arrego de la interface de "ventas" (no figura stock del producto vendido)

* Creación de "DEPOSITO" donde se suman todos los "DEPOSITOS" de cada cierre y se restan los GASTOS que sean espeficiados que son de deposito. (que genere un reporte de cuanto hay en la "caja fuerte" del local. y agregar la opcion de editarlo o dejarlo en 0

**Comment by Kamesta** [comment]
Existencias - Crear categoria TODOS entre los items a ver "existencias"
HECHO, tocar directamente la lupa


    Existencias - que genere, por local un historial "anual" de X fecha a X fecha puede tomar los intervalos cada 15 dias por ej. y poder exportarlo a un xls.
HECHO, pero sin testear a fondo, con la db chica de test carga rapido y hace todo, pero con la db de produccion, tarda mucho, (corre en segundo plano para no molestar a los usuarios del sistema y cada 15 dias a las 15:00hs)

    Implementar las comisiones entre las estadisticas
PENDIENTE

    Restas de stock x mes o fecha especifica y que user lo realizo (actualmente en eventos te mezcla todo y es complicado encontrar las restas de stock para control )
HECHO 

    Arrego de la interface de "ventas" (no figura stock del producto vendido)
CONTROLADO, esta andando el stock actual y el de otros locales

    Creación de "DEPOSITO" donde se suman todos los "DEPOSITOS" de cada cierre y se restan los GASTOS que sean espeficiados que son de deposito. (que genere un reporte de cuanto hay en la "caja fuerte" del local. y agregar la opcion de editarlo o dejarlo en 0
PENDIENTE


Abrir los issues por separado asi puedo cerrarlos por partes etc

**Comment by CostanzoPablo** [comment]
Existencias - Crear categoria TODOS entre los items a ver "existencias"
HECHO, tocar directamente la lupa


    Existencias - que genere, por local un historial "anual" de X fecha a X fecha puede tomar los intervalos cada 15 dias por ej. y poder exportarlo a un xls.
HECHO, pero sin testear a fondo, con la db chica de test carga rapido y hace todo, pero con la db de produccion, tarda mucho, (corre en segundo plano para no molestar a los usuarios del sistema y cada 15 dias a las 15:00hs)

    Implementar las comisiones entre las estadisticas
PENDIENTE

    Restas de stock x mes o fecha especifica y que user lo realizo (actualmente en eventos te mezcla todo y es complicado encontrar las restas de stock para control )
HECHO 

    Arrego de la interface de "ventas" (no figura stock del producto vendido)
CONTROLADO, esta andando el stock actual y el de otros locales

    Creación de "DEPOSITO" donde se suman todos los "DEPOSITOS" de cada cierre y se restan los GASTOS que sean espeficiados que son de deposito. (que genere un reporte de cuanto hay en la "caja fuerte" del local. y agregar la opcion de editarlo o dejarlo en 0
PENDIENTE


Abrir los issues por separado asi puedo cerrarlos por partes etc
