### ISSUE TITLE
Ventas Online:

### ISSUE THREAD

**Issue by Kamesta** [CostanzoPablo/shell#37]
Creacion de una interface para ingresar las ventas "online" que suelen tener comisiones asociadas:

* Producto: (poder seleccionar con el buscador o con upc )
* Canal: (poder asociar las comisiones al canal especifico: "Mercadolibre" o "Mercadolibre Nacho" )
(en este caso mercadolibre no lleva comision, pero si mercado libre nacho)
* Poder asignar comisiones a los distintos "Canales"
* Las comisiones se asignan al usuario que carga los datos.
* Direccion (para envios a domicilio, poder consultar los datos) De ser posible, que aparezca una leyenda que recuerde ingresar los datos (Direccion+Telefono+horario)
* Creacion de las estadisticas y poder consultarlas (para saber que comisiones tiene que cobrar el vendedor).
* Al confirmar la operacion, que reste el producto de stock, logee y que deje seleccionar desde que sucursal se envia para que reste de esa sucursal.

**Comment by Kamesta** [comment]
PENDIENTE

**Comment by CostanzoPablo** [comment]
Atendiendo...
