### ISSUE TITLE
Pedidos - Stock maximo 0

### ISSUE THREAD

**Issue by Kamesta** [CostanzoPablo/shell#46]
Al Eliminar de la lista de pedidos un producto, vuelve a la raiz de todo y hay que seleccionar nuevamente que categoria ir para seguir eliminando productos, 

Tendrias que permanecer en la opcion seleccionada .

**Comment by CostanzoPablo** [comment]
Bien, y por mas que se auto marque luego de eliminarlo, si el pedido es grande, tarda en procesarlo. Para solucionar esto, la eliminacion se ejecuta en nueva ventana.
