### ISSUE TITLE
Existencias No funciona

### ISSUE THREAD

**Issue by Kamesta** [CostanzoPablo/shell#47]
Existencias no funciona , no se si estara funcionando el historial, pero cuando seleccionas los rubros te tira cualquier cosa.

Y Estaria bueno que cuando funcione, no agrupe los rubros, por ej , juegos divida , juegos de ps3, ps4, xbox1, etc...

**Comment by CostanzoPablo** [comment]
Ok. Tendria que verlo ahi mismo porque no corre el .bat

**Comment by CostanzoPablo** [comment]
Ya esta andando bien. Si continuan los problemas, es culpa del cron scheduler del servidor. Verificar que este correctamente cargada la tarea. En el servidor se puede probar yendo a c:\xampp\httdocs\cron.bat (generara las existencias del mes actual)
